package uniza.fri.majba.dis1.traversal_simulation.graph;

import uniza.fri.majba.dis1.simulation_core.generators.Generator;

public class Edge<V> {
    private final V from;
    private final V to;
    private final EdgeColor edgeColor;
    private final int weight;
    private final Generator generator;

    public Edge(V from, V to, EdgeColor edgeColor, int weight, Generator generator) {
        this.from = from;
        this.to = to;
        this.edgeColor = edgeColor;
        this.weight = weight;
        this.generator = generator;
    }

    public V from() {
        return from;
    }

    public V to() {
        return to;
    }

    public EdgeColor edgeColor() {
        return edgeColor;
    }

    public int weight() {
        return weight;
    }

    public Generator generator() {
        return generator;
    }

    /**
     * Calculates the traversal time of the edge based on its weight and the average speed generated by the generator.
     * @param departureTime The simulation time (in hours) at which the courier departs onto this edge.
     * @return The traversal time of the edge.
     */
    public double getTraversalTime(double departureTime) {
        return weight / generator.generate();
    }
}
