package uniza.fri.majba.dis1.traversal_simulation.graph;

import uniza.fri.majba.dis1.simulation_core.generators.Generator;

/**
 * @param from      The start node of the edge.
 * @param to        The end node of the edge.
 * @param edgeColor The color of the edge - represents the average speed on the edge.
 * @param weight    The weight of the edge - represents the length of the edge
 * @param generator The generator that generates the traversal average speed on this edge.
 */
public record Edge<V>(V from, V to, EdgeColor edgeColor, int weight, Generator generator) {
    /**
     * Calculates the traversal time of the edge based on its weight and the average speed generated by the generator.
     * @return The traversal time of the edge.
     */
    public double getTraversalTime() {
        return weight / generator.generate();
    }
}
